spring.config.import=optional:file:.env[.properties]

logging.level.me.paulschwarz=DEBUG

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.auto-index-creation=false

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}

aws.region=${AWS_REGION:ap-southeast-1}
aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}
app.cdn-domain=${APP_CDN_DOMAIN}

jwt.secret-key=${JWT_SECRET_KEY}

aws.cognito.userPoolId=${AWS_COGNITO_USER_POOL_ID}
aws.cognito.clientId=${AWS_COGNITO_CLIENT_ID}

ai.provider.base-url=${AI_PROVIDER_BASE_URL}
ai.provider.api-key=${AI_PROVIDER_API_KEY}

app.web-url=${APP_WEB_URL:http://localhost:5173}


