spring.application.name=user-chat-service

server.port=8082

media.service.base-url=${MEDIA_SERVICE_BASE_URL:http://localhost:8081}

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=false
